### PR TITLE
Added `ak.mapRecords()` method

### PR DESCRIPTION
**Pull request by SupremeTechnopriest**
example

``` javascript
var map = ak.mapRecords(function(record, i) {
    return record.id + '-' + i;
});
```

This will return an array of `[ id-index ]`.  It doesn't mutate your internal state, just returns a clone with the supplied transform applied.

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
What do you think of this addition?  Can we get a merge and a bump if it looks ok?  Otherwise I'll just maintain my own fork.

**Comment by silverbucket** [comment]
Yes looks good, will merge and bump the version within a day or so.

**Comment by SupremeTechnopriest** [comment]
Great thanks!

**Comment by silverbucket** [comment]
Thanks a lot for the pull request @SupremeTechnopriest - merging and bumping now

**Comment by SupremeTechnopriest** [comment]
No problem!  Thanks for the project.  It's great.

**Pull request merged**
